apiVersion: v1
kind: Service
metadata:
  name: ordering-svc
  labels:
    app: fastTechFoods
    service: ordering-api
spec:
  selector:
    app: fastTechFoods
    service: ordering-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080